apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-sfbvdfck
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-sfbvdfck:a01f904f6973603ea95ec13a401d3817e0aa6f6d@sha256:4b633371b8b2ad6dc0c4864bf54f4131ea710f5d3bf7d3d5e92266c491d0d2ab
          name: container-image
